name: Python package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests pyjson5 python_nbt
    - name: Run the custom Python script
      run: |
        python neunscript.py
      working-directory: ${{ github.workspace }}
    - name: Create dist folder
      run: |
        mkdir dist
      working-directory: ${{ github.workspace }}
    - name: Move files to dist folder
      run: |
        mv /path/to/generated/files/* dist/
      working-directory: ${{ github.workspace }}
